# Generated by Django 4.0.3 on 2022-05-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_1.png', null=True, upload_to=''),
        ),
    ]
